create extension if not exists pgcrypto;

create type public.request_status as enum (
  'submitted',
  'under_review',
  'approved',
  'driver_assigned',
  'heading_to_pickup',
  'picked_up',
  'out_for_delivery',
  'delivered',
  'not_delivered',
  'denied'
);

create type public.driver_application_status as enum ('pending', 'approved', 'denied');

create table public.seasons (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) > 0),
  starts_on date,
  ends_on date,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on is null or starts_on is null or ends_on >= starts_on)
);

create unique index seasons_one_active_idx on public.seasons (is_active) where is_active;

create table public.driver_applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  phone text not null check (length(trim(phone)) > 0),
  email text not null check (length(trim(email)) > 0),
  status public.driver_application_status not null default 'pending',
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index driver_applications_email_idx on public.driver_applications (lower(email));

create table public.distribution_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity (start with 1000),
  owner_id uuid not null references auth.users(id) on delete restrict,
  season_id uuid not null references public.seasons(id) on delete restrict,
  recipient_name text not null check (length(trim(recipient_name)) > 0),
  phone text not null check (length(trim(phone)) > 0),
  email text not null check (length(trim(email)) > 0),
  address text not null check (length(trim(address)) > 0),
  household_size integer not null check (household_size > 0),
  box_weight_lbs integer not null check (box_weight_lbs > 0),
  instructions text not null,
  status public.request_status not null default 'submitted',
  assigned_driver_id uuid references public.driver_applications(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, season_id)
);

create unique index distribution_requests_season_email_idx
  on public.distribution_requests (season_id, lower(email));
create unique index distribution_requests_season_phone_idx
  on public.distribution_requests (season_id, regexp_replace(phone, '[^0-9]', '', 'g'));
create index distribution_requests_status_idx on public.distribution_requests (season_id, status);
create index distribution_requests_driver_idx on public.distribution_requests (assigned_driver_id, status);

create table public.delivery_events (
  id bigint generated always as identity primary key,
  request_id uuid not null references public.distribution_requests(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null check (length(trim(event_type)) > 0),
  from_status public.request_status,
  to_status public.request_status,
  notes text,
  created_at timestamptz not null default now()
);

create index delivery_events_request_idx on public.delivery_events (request_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger seasons_set_updated_at
before update on public.seasons
for each row execute function public.set_updated_at();

create trigger driver_applications_set_updated_at
before update on public.driver_applications
for each row execute function public.set_updated_at();

create trigger distribution_requests_set_updated_at
before update on public.distribution_requests
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false);
$$;

create or replace function public.is_approved_driver(candidate uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.driver_applications
    where user_id = candidate and status = 'approved'
  );
$$;

revoke all on function public.is_admin() from public;
revoke all on function public.is_approved_driver(uuid) from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_approved_driver(uuid) to authenticated;

alter table public.seasons enable row level security;
alter table public.driver_applications enable row level security;
alter table public.distribution_requests enable row level security;
alter table public.delivery_events enable row level security;

create policy "authenticated users can read seasons"
on public.seasons for select to authenticated
using (true);

create policy "admins manage seasons"
on public.seasons for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "users read their driver application"
on public.driver_applications for select to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "users create their driver application"
on public.driver_applications for insert to authenticated
with check (user_id = auth.uid() and status = 'pending');

create policy "users resubmit a denied driver application"
on public.driver_applications for update to authenticated
using (user_id = auth.uid() and status = 'denied')
with check (user_id = auth.uid() and status = 'pending' and reviewed_by is null and reviewed_at is null);

create policy "admins update driver applications"
on public.driver_applications for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "recipients read their requests"
on public.distribution_requests for select to authenticated
using (owner_id = auth.uid());

create policy "approved drivers read available and assigned requests"
on public.distribution_requests for select to authenticated
using (
  public.is_approved_driver()
  and (
    status in ('approved', 'not_delivered')
    or assigned_driver_id = auth.uid()
  )
);

create policy "admins read all requests"
on public.distribution_requests for select to authenticated
using (public.is_admin());

create policy "recipients create their requests"
on public.distribution_requests for insert to authenticated
with check (owner_id = auth.uid() and status = 'submitted' and assigned_driver_id is null);

create policy "admins update requests"
on public.distribution_requests for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "request participants read delivery events"
on public.delivery_events for select to authenticated
using (
  public.is_admin()
  or actor_id = auth.uid()
  or exists (
    select 1 from public.distribution_requests request
    where request.id = request_id
      and (request.owner_id = auth.uid() or request.assigned_driver_id = auth.uid())
  )
);

create or replace function public.claim_delivery(target_request_id uuid)
returns public.distribution_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  claimed public.distribution_requests;
  previous_status public.request_status;
begin
  if auth.uid() is null or not public.is_approved_driver(auth.uid()) then
    raise exception 'Only approved drivers can claim deliveries';
  end if;

  select status into previous_status
  from public.distribution_requests
  where id = target_request_id
    and status in ('approved', 'not_delivered')
    and (assigned_driver_id is null or status = 'not_delivered')
  for update;

  update public.distribution_requests
  set assigned_driver_id = auth.uid(), status = 'driver_assigned'
  where id = target_request_id
    and status in ('approved', 'not_delivered')
    and (assigned_driver_id is null or status = 'not_delivered')
  returning * into claimed;

  if claimed.id is null then
    raise exception 'Delivery is no longer available';
  end if;

  insert into public.delivery_events (request_id, actor_id, event_type, from_status, to_status)
  values (claimed.id, auth.uid(), 'claimed', previous_status, 'driver_assigned');

  return claimed;
end;
$$;

create or replace function public.assign_delivery(target_request_id uuid, target_driver_id uuid)
returns public.distribution_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  assigned public.distribution_requests;
  previous_status public.request_status;
begin
  if not public.is_admin() then
    raise exception 'Only admins can assign deliveries';
  end if;

  if not public.is_approved_driver(target_driver_id) then
    raise exception 'The selected driver is not approved';
  end if;

  select status into previous_status
  from public.distribution_requests
  where id = target_request_id
    and status in ('approved', 'not_delivered')
  for update;

  update public.distribution_requests
  set assigned_driver_id = target_driver_id, status = 'driver_assigned'
  where id = target_request_id and status in ('approved', 'not_delivered')
  returning * into assigned;

  if assigned.id is null then
    raise exception 'Delivery is no longer available';
  end if;

  insert into public.delivery_events (request_id, actor_id, event_type, from_status, to_status, notes)
  values (assigned.id, auth.uid(), 'assigned', previous_status, 'driver_assigned', target_driver_id::text);

  return assigned;
end;
$$;

create or replace function public.unclaim_delivery(target_request_id uuid)
returns public.distribution_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  released public.distribution_requests;
begin
  update public.distribution_requests
  set assigned_driver_id = null, status = 'approved'
  where id = target_request_id
    and assigned_driver_id = auth.uid()
    and status = 'driver_assigned'
  returning * into released;

  if released.id is null then
    raise exception 'Only the assigned driver can unclaim this delivery';
  end if;

  insert into public.delivery_events (request_id, actor_id, event_type, from_status, to_status)
  values (released.id, auth.uid(), 'unclaimed', 'driver_assigned', 'approved');

  return released;
end;
$$;

create or replace function public.set_delivery_status(target_request_id uuid, next_status public.request_status)
returns public.distribution_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_request public.distribution_requests;
  changed public.distribution_requests;
begin
  select * into current_request
  from public.distribution_requests
  where id = target_request_id
  for update;

  if current_request.id is null then
    raise exception 'Delivery not found';
  end if;

  if not public.is_admin() and current_request.assigned_driver_id <> auth.uid() then
    raise exception 'Only the assigned driver can update this delivery';
  end if;

  if next_status not in ('heading_to_pickup', 'picked_up', 'out_for_delivery', 'delivered', 'not_delivered') then
    raise exception 'Unsupported delivery status';
  end if;

  if next_status = 'heading_to_pickup' and current_request.status <> 'driver_assigned' then
    raise exception 'Delivery must be assigned before pickup starts';
  end if;

  if next_status = 'picked_up' and current_request.status not in ('driver_assigned', 'heading_to_pickup') then
    raise exception 'Driver must be heading to pickup before confirming pickup';
  end if;

  if next_status = 'out_for_delivery' and current_request.status <> 'picked_up' then
    raise exception 'Delivery must be picked up before starting the route';
  end if;

  if next_status in ('delivered', 'not_delivered') and current_request.status <> 'out_for_delivery' then
    raise exception 'Delivery is not ready to be completed';
  end if;

  update public.distribution_requests
  set status = next_status
  where id = target_request_id
  returning * into changed;

  insert into public.delivery_events (request_id, actor_id, event_type, from_status, to_status)
  values (changed.id, auth.uid(), 'status_changed', current_request.status, changed.status);

  return changed;
end;
$$;

create or replace function public.activate_season(season_name text, season_starts_on date, season_ends_on date)
returns public.seasons
language plpgsql
security definer
set search_path = ''
as $$
declare
  activated public.seasons;
begin
  if not public.is_admin() then
    raise exception 'Only admins can manage seasons';
  end if;

  if length(trim(season_name)) = 0 then
    raise exception 'Season name is required';
  end if;

  if season_ends_on is not null and season_starts_on is not null and season_ends_on < season_starts_on then
    raise exception 'Season end date must be after its start date';
  end if;

  update public.seasons set is_active = false where is_active;
  insert into public.seasons (name, starts_on, ends_on, is_active)
  values (trim(season_name), season_starts_on, season_ends_on, true)
  returning * into activated;

  return activated;
end;
$$;

revoke all on function public.claim_delivery(uuid) from public;
revoke all on function public.assign_delivery(uuid, uuid) from public;
revoke all on function public.unclaim_delivery(uuid) from public;
revoke all on function public.set_delivery_status(uuid, public.request_status) from public;
revoke all on function public.activate_season(text, date, date) from public;
grant execute on function public.claim_delivery(uuid) to authenticated;
grant execute on function public.assign_delivery(uuid, uuid) to authenticated;
grant execute on function public.unclaim_delivery(uuid) to authenticated;
grant execute on function public.set_delivery_status(uuid, public.request_status) to authenticated;
grant execute on function public.activate_season(text, date, date) to authenticated;

insert into public.seasons (name, starts_on, ends_on, is_active)
values ('Ramadan 2026', '2026-02-18', '2026-03-19', true);
